In [285]:
# Config Data Structure
import pandas as pd
from datetime import datetime as dt
from pymongo import MongoClient as mc
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences
from collections import Counter
import pprint as pp
import random as ran
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN, LSTM
from tensorflow.keras.utils import to_categorical
from functools import reduce
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(rc={'figure.figsize': (15.7, 13.27)})
plt.rcParams['figure.figsize'] = 15.7,13.27
plt.rcParams['font.family'] = 'AppleGothic'

mongo_uri = "mongodb://localhost:27017"
client = mc(mongo_uri)
keti_db = client.keti_pattern_recognition

household_col = keti_db.household_info
weather_col = keti_db.weather_info

In [286]:
# TimeSlot In
hh_db_datas = household_col.find_one({"uid": "아파트1-101-1602"})
hh_db_datas

uid_in, timeslot = hh_db_datas['uid'], hh_db_datas['timeslot']

datelist = [
    dt.strptime(ts['time'], "%Y-%m-%d T%H:%M %z").date()
    for ts in timeslot
]
datelist = list(set(datelist))
datelist.sort()

ts_datas = {}
start_idx = 0
end_idx = 96
enl = 1

for date in datelist:
    ts_datas[date] = [ts['power'] *
                      enl for ts in timeslot[start_idx:end_idx]]
    start_idx = end_idx
    end_idx = end_idx + 96

ts_datas = pd.DataFrame(ts_datas).T
hh_datas = ts_datas.reset_index().copy()

hh_datas.rename(columns={"index": "date"}, inplace=True)
hh_datas['date'] = pd.to_datetime(hh_datas['date'])

hh_datas.set_index('date', inplace=True)

# Merging
merge_size = 4
merge_datas = pd.DataFrame()
for date in hh_datas.index:
    merge_ts = []
    new_ts_size = round(len(hh_datas.loc[date]) / merge_size)
    
    for idx in range(0,new_ts_size):
        merge_ts.append(
            round(hh_datas.loc[date][merge_size * idx:merge_size * (idx + 1)].sum(), 3) * 1000
        )
    if len(list(set(merge_ts))) >= 3:
        merge_datas[date] = merge_ts
    
def get_season_no(month):
    if month in [3,4,5]:
        return 1 # 봄
    elif month in [6,7,8]:
        return 2 # 여름
    elif month in [9,10,11]:
        return 3 # 가을
    elif month in [12,1,2]:
        return 4 # 겨울
    
# separate_datas_col = list(filter(lambda data: get_season_no(data.month) == 4, merge_datas.columns))
# print(separate_datas_col)
# merge_datas = merge_datas[separate_datas_col]
merge_datas

2018-05-01  2018-05-02  2018-05-03  2018-05-04  2018-05-05  2018-05-06  \
0        431.0       286.0       434.0       280.0       143.0       216.0   
1        178.0       265.0       316.0       266.0       124.0       211.0   
2        205.0       306.0       238.0       234.0       143.0       228.0   
3        198.0       290.0       269.0       317.0       135.0       322.0   
4        204.0       270.0       335.0       236.0       149.0       269.0   
5        251.0       283.0       271.0       240.0       268.0       216.0   
6        231.0       525.0       722.0      1088.0       219.0       228.0   
7        234.0       350.0       403.0       348.0       307.0       237.0   
8        228.0       340.0       445.0       481.0       243.0       261.0   
9        328.0       207.0       402.0       446.0       305.0       215.0   
10       466.0       189.0       301.0       682.0       210.0       223.0   
11       437.0       398.0       314.0       209.0       160.0       225.0   
12       935.0       480.0       327.0       215.0       127.0       285.0   
13       442.0       803.0       404.0       191.0       163.0       240.0   
14       278.0       340.0       363.0       134.0       145.0       212.0   
15       337.0       165.0       234.0       151.0       225.0       248.0   
16       406.0       396.0       227.0       126.0       276.0       257.0   
17       450.0       366.0       238.0       171.0       314.0       216.0   
18       767.0       604.0       292.0       136.0       247.0       752.0   
19       942.0       476.0       237.0       139.0       244.0       701.0   
20       794.0       456.0       347.0       174.0       366.0       522.0   
21       715.0       512.0       451.0       147.0       245.0       450.0   
22       605.0       552.0       442.0       136.0       239.0       499.0   
23       305.0       519.0       453.0       168.0       230.0       425.0   

    2018-05-07  2018-05-08  2018-05-09  2018-05-10  ...  2019-04-21  \
0        438.0       206.0       298.0       471.0  ...       264.0   
1        344.0       156.0       264.0       223.0  ...       235.0   
2        317.0       154.0       255.0       282.0  ...       217.0   
3        379.0       155.0       235.0       269.0  ...       248.0   
4        332.0       169.0       261.0       293.0  ...       256.0   
5        258.0       325.0       283.0       287.0  ...       227.0   
6        205.0       454.0       510.0       702.0  ...       224.0   
7        222.0       150.0       291.0       667.0  ...       232.0   
8        266.0       146.0       269.0       297.0  ...       234.0   
9        545.0       207.0       360.0       305.0  ...       252.0   
10       517.0       410.0       290.0       417.0  ...       280.0   
11       738.0       299.0       250.0       543.0  ...       237.0   
12       481.0       216.0       328.0       648.0  ...       238.0   
13       897.0       155.0       348.0       577.0  ...       246.0   
14       410.0       186.0       355.0       294.0  ...       225.0   
15       380.0       189.0       415.0       313.0  ...       333.0   
16       411.0       183.0       461.0       437.0  ...       877.0   
17       369.0       177.0       547.0       689.0  ...       931.0   
18       440.0       181.0       386.0       639.0  ...      1489.0   
19       611.0       182.0       399.0       465.0  ...      1349.0   
20       585.0       203.0       423.0      1007.0  ...       521.0   
21       585.0       345.0       453.0       799.0  ...       714.0   
22       795.0       346.0       446.0       725.0  ...       679.0   
23       483.0       291.0       425.0       554.0  ...       692.0   

    2019-04-22  2019-04-23  2019-04-24  2019-04-25  2019-04-26  2019-04-27  \
0        462.0       315.0       456.0       388.0       462.0       502.0   
1        455.0       316.0       462.0       361.0       427.0       345.0   
2        494.0       315.0       363.0     

In [287]:
# Set Test Datas
# 계절별 10% 랜덤하게
def get_season_no(month):
    if month in [3,4,5]:
        return 1 # 봄
    elif month in [6,7,8]:
        return 2 # 여름
    elif month in [9,10,11]:
        return 3 # 가을
    elif month in [12,1,2]:
        return 4 # 겨울
    
test_merge_datas = pd.DataFrame();

for i in range(1,5):
    filter_list = list(filter(lambda date: get_season_no(date.month) == i, merge_datas.columns))
    test_list_idx = list()
    while True:
        filter_data = filter_list[ran.randrange(0,len(filter_list))]
        if filter_data not in test_list_idx:
            test_list_idx.append(filter_data)
            
        if len(test_list_idx) >= (len(filter_list) * 15 / 100):
            break;
    test_merge_datas = pd.concat([test_merge_datas, merge_datas[test_list_idx]], axis=1)
    merge_datas.drop(test_list_idx, axis=1, inplace=True)

test_merge_datas

2019-03-30  2019-04-23  2018-05-23  2018-05-29  2019-04-16  2019-04-13  \
0        748.0       315.0       277.0       296.0       574.0       254.0   
1        633.0       316.0       272.0       274.0       512.0       284.0   
2        531.0       315.0       242.0       289.0       430.0       438.0   
3        453.0       355.0       323.0       271.0       413.0       321.0   
4        454.0       296.0       243.0       251.0       403.0       275.0   
5        549.0       354.0       272.0       281.0       376.0       312.0   
6        490.0       538.0       495.0       465.0       743.0       493.0   
7        431.0       457.0       387.0       280.0       354.0       305.0   
8        500.0       398.0       833.0       527.0       263.0       351.0   
9        871.0       243.0       539.0       371.0       265.0       345.0   
10       603.0       273.0       248.0       338.0       426.0       579.0   
11       670.0       247.0       135.0       369.0      1023.0       449.0   
12       490.0       227.0       152.0       440.0       487.0       460.0   
13       501.0       293.0       137.0       393.0      1075.0       348.0   
14       485.0       335.0       141.0       440.0      1101.0       326.0   
15       523.0       416.0       297.0       406.0       653.0       340.0   
16       458.0       438.0       357.0       232.0       467.0       430.0   
17       188.0       572.0       253.0       716.0       758.0       392.0   
18       182.0       424.0       232.0       615.0       557.0       357.0   
19       194.0       465.0       221.0       623.0       694.0       529.0   
20       208.0       471.0       232.0       456.0       829.0       669.0   
21       183.0       368.0       205.0       490.0       751.0       754.0   
22       185.0       488.0       213.0       417.0       710.0       646.0   
23       309.0       517.0       424.0       365.0       427.0       618.0   

    2018-05-05  2019-03-01  2019-04-22  2018-05-17  ...  2018-12-01  \
0        143.0       489.0       462.0       410.0  ...       302.0   
1        124.0       519.0       455.0       450.0  ...       285.0   
2        143.0       413.0       494.0       317.0  ...       272.0   
3        135.0       309.0       413.0       300.0  ...       346.0   
4        149.0       262.0       390.0       304.0  ...       302.0   
5        268.0       233.0       595.0       339.0  ...       431.0   
6        219.0       263.0       854.0       706.0  ...       281.0   
7        307.0       421.0       616.0       400.0  ...       613.0   
8        243.0       529.0       388.0       416.0  ...       536.0   
9        305.0       510.0       326.0       288.0  ...       541.0   
10       210.0       820.0       618.0       162.0  ...       456.0   
11       160.0       363.0       796.0       285.0  ...       310.0   
12       127.0       297.0       571.0       850.0  ...      1025.0   
13       163.0       343.0       689.0       490.0  ...       614.0   
14       145.0       278.0       545.0       231.0  ...       470.0   
15       225.0       310.0       950.0       426.0  ...      1004.0   
16       276.0       283.0       507.0       704.0  ...       484.0   
17       314.0       292.0      1146.0       534.0  ...       517.0   
18       247.0       327.0       846.0       785.0  ...       440.0   
19       244.0       524.0       551.0       845.0  ...       473.0   
20       366.0      1228.0       607.0       850.0  ...       402.0   
21       245.0       441.0       557.0       848.0  ...       663.0   
22       239.0       543.0       519.0       804.0  ...       371.0   
23       230.0       704.0       286.0       690.0  ...       341.0   

    2019-02-26  2019-01-28  2019-02-28  2019-01-20  2019-02-10  2018-12-05  \
0        383.0       375.0       327.0       447.0       538.0       349.0   
1        455.0       344.0       329.0       560.0       502.0       223.0   
2        305.0       392.0       395.0     

In [288]:
y = reduce(lambda acc, cur: cur + acc ,merge_datas.values.tolist(), [])
value_size = len(y)
print(value_size)

7344


In [289]:
# Config Training Datas
wt_db_datas = weather_col.find()
wt_datas = pd.DataFrame()

for wt in wt_db_datas:
    tmp = pd.DataFrame()
    tmp['date'] = [wt['date']]
    tmp['weather'] = [wt['weather']]
    tmp['avg_ta'] = round(float(wt['avgTa']))
    tmp['avg_rhm'] = round(float(wt['avgRhm']))
    
    wt_datas = pd.concat([wt_datas, tmp])

# 영하 온도 전처리
min_ta = min(wt_datas['avg_ta'])
wt_datas['avg_ta'] += (min_ta * -1 + 1)
min(wt_datas['avg_ta'])

1

In [290]:
# weather 정수 인코딩
weather_count = Counter(wt_datas['weather'])
weather_integer = dict()
rank = 1
for key, count in weather_count.most_common():
    weather_integer[key] = rank
    rank += 1
pp.pprint(weather_integer)
wt_datas['weather_no'] = [weather_integer[weather] for weather in wt_datas['weather']]
wt_datas

def get_season_no(month):
    if month in [3,4,5]:
        return 1 # 봄
    elif month in [6,7,8]:
        return 2 # 여름
    elif month in [9,10,11]:
        return 3 # 가을
    elif month in [12,1,2]:
        return 4 # 겨울
    
# Date, Season Utils
wt_datas['season_no'] = [get_season_no(weather.month) for weather in wt_datas['date']] 
wt_datas['day_no'] = [weather.weekday() + 1 for weather in wt_datas['date']] 

sample_weather_col = ['season_no','day_no','weather_no','avg_ta', 'avg_rhm']
sample_weather_col_2 = ['date','season_no','day_no','weather','weather_no','avg_ta', 'avg_rhm']
wt_datas[sample_weather_col_2]

{'눈': 5,
 '박무': 4,
 '비': 3,
 '소나기': 7,
 '안개': 10,
 '안개비': 11,
 '연무': 2,
 '진눈깨비': 12,
 '채운': 8,
 '특이사항 없음': 1,
 '햇무리': 6,
 '황사': 9}


date  season_no  day_no  weather  weather_no  avg_ta  avg_rhm
0  2018-05-01          1       2       연무           2      31       73
0  2018-05-02          1       3        비           3      26       90
0  2018-05-03          1       4        비           3      22       62
0  2018-05-04          1       5  특이사항 없음           1      25       46
0  2018-05-05          1       6  특이사항 없음           1      29       47
..        ...        ...     ...      ...         ...     ...      ...
0  2019-04-26          1       5        비           3      19       82
0  2019-04-27          1       6      햇무리           6      23       53
0  2019-04-28          1       7        비           3      24       49
0  2019-04-29          1       1      햇무리           6      24       53
0  2019-04-30          1       2      햇무리           6      27       53

[365 rows x 7 columns]

In [291]:
# Config Sample Datas - Padding
# Data Preprocessing
def get_samples(datas):
    samples = list()
    for col in datas:
        timeslot = datas[col].values.tolist()
        weather = wt_datas[wt_datas['date'] == col][sample_weather_col].values.tolist()[0]
        for time in range(1,25):
            samples.append(weather + timeslot[:time])

    print("Samples Before Padding Process")
    print(np.array(samples))
    print("\nTranining Sample Size : {}".format(len(samples)))
    
    return samples

def get_padding_samples(samples):    
    # Padding
    pad_samples = list()
    SAMPLE_MAX_LEN = max([len(s) for s in samples])
    print("Tranining Sample MAX_LEN : {}".format(SAMPLE_MAX_LEN))
    for sample in samples:
        err = SAMPLE_MAX_LEN - len(sample)
        if err == 0:
            pad_samples.append(sample)
        else:
            pad_data = [0 for i in range(0, err)]
            pad_samples.append(pad_data + sample)
    print("\nFinal Samples")
    print(np.array(pad_samples))
    
    return pad_samples
    
test_samples = get_samples(test_merge_datas)
test_samples = get_padding_samples(test_samples)

training_samples = get_samples(merge_datas)
training_samples = get_padding_samples(training_samples)

Samples Before Padding Process
[list([1, 6, 3, 16, 72, 748.0]) list([1, 6, 3, 16, 72, 748.0, 633.0])
 list([1, 6, 3, 16, 72, 748.0, 633.0, 531.0]) ...
 list([4, 1, 2, 13, 60, 409.0, 526.0, 488.0, 433.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 370.0, 725.0, 498.0, 506.0, 551.0, 691.0])
 list([4, 1, 2, 13, 60, 409.0, 526.0, 488.0, 433.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 370.0, 725.0, 498.0, 506.0, 551.0, 691.0, 657.0])
 list([4, 1, 2, 13, 60, 409.0, 526.0, 488.0, 433.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 376.0, 370.0, 725.0, 498.0, 506.0, 551.0, 691.0, 657.0, 662.0])]

Tranining Sample Size : 1344
Tranining Sample MAX_LEN : 29

Final Samples
[[  0.   0.   0. ...  16.  72. 748.]
 [  0.   0.   0. ...  72. 748. 633.]
 [  0.   0.   0. ... 748. 633. 531.]
 ...
 [  0.   0.   4. ... 506. 551. 691.]
 [  0.   4.   1. ... 551. 691. 657.]
 [  4.   1.   2. ... 691.

<ipython-input-291-f7267c0eac4d>:12: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  print(np.array(samples))


In [292]:
# Set Tranining Data
training_samples = np.array(training_samples)

train_X = training_samples[:,:-1]
train_y = training_samples[:,-1]

# Set Test Data
test_samples = np.array(test_samples)
test_X = test_samples[:,:-1]
test_y = test_samples[:,-1]

print("Input Data For Training")
print(np.array(train_X))
print()
print("Output Data For Training")
print(np.array(train_y))

print("Input Data For Test")
print(np.array(test_X))
print()
print("Output Data For Test")
print(np.array(test_y))

Input Data For Training
[[  0.   0.   0. ...   2.  31.  73.]
 [  0.   0.   0. ...  31.  73. 431.]
 [  0.   0.   0. ...  73. 431. 178.]
 ...
 [  0.   0.   1. ... 897. 426. 516.]
 [  0.   1.   2. ... 426. 516. 561.]
 [  1.   2.   6. ... 516. 561. 549.]]

Output Data For Training
[431. 178. 205. ... 561. 549. 551.]
Input Data For Test
[[  0.   0.   0. ...   3.  16.  72.]
 [  0.   0.   0. ...  16.  72. 748.]
 [  0.   0.   0. ...  72. 748. 633.]
 ...
 [  0.   0.   4. ... 498. 506. 551.]
 [  0.   4.   1. ... 506. 551. 691.]
 [  4.   1.   2. ... 551. 691. 657.]]

Output Data For Test
[748. 633. 531. ... 691. 657. 662.]


In [293]:
one_hot_y = to_categorical(train_y,num_classes=value_size)
one_hot_y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [301]:
model_2 = Sequential(name="rnn-model-1-101-1602")
model_2.add(Embedding(value_size, 10, input_length=28))
model_2.add(LSTM(128))
model_2.add(Dense(value_size, activation='softmax'))
model_2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model_2.summary()

Model: "rnn-model-1-101-1602"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_26 (Embedding)     (None, 28, 10)            73440     
_________________________________________________________________
lstm_27 (LSTM)               (None, 128)               71168     
_________________________________________________________________
dense_27 (Dense)             (None, 7344)              947376    
Total params: 1,091,984
Trainable params: 1,091,984
Non-trainable params: 0
_________________________________________________________________


In [302]:
model_2.fit(train_X, one_hot_y, epochs=400, verbose=2)

Epoch 1/400
230/230 - 5s - loss: 7.4159 - accuracy: 0.0034
Epoch 2/400
230/230 - 3s - loss: 6.7314 - accuracy: 0.0050
Epoch 3/400
230/230 - 4s - loss: 6.6666 - accuracy: 0.0042
Epoch 4/400
230/230 - 4s - loss: 6.6219 - accuracy: 0.0050
Epoch 5/400
230/230 - 4s - loss: 6.5734 - accuracy: 0.0053
Epoch 6/400
230/230 - 3s - loss: 6.5039 - accuracy: 0.0061
Epoch 7/400
230/230 - 3s - loss: 6.4165 - accuracy: 0.0060
Epoch 8/400
230/230 - 3s - loss: 6.3265 - accuracy: 0.0078
Epoch 9/400
230/230 - 3s - loss: 6.2375 - accuracy: 0.0079
Epoch 10/400
230/230 - 3s - loss: 6.1486 - accuracy: 0.0082
Epoch 11/400
230/230 - 3s - loss: 6.0589 - accuracy: 0.0109
Epoch 12/400
230/230 - 3s - loss: 5.9661 - accuracy: 0.0131
Epoch 13/400
230/230 - 3s - loss: 5.8720 - accuracy: 0.0157
Epoch 14/400
230/230 - 3s - loss: 5.7839 - accuracy: 0.0182
Epoch 15/400
230/230 - 4s - loss: 5.6940 - accuracy: 0.0202
Epoch 16/400
230/230 - 4s - loss: 5.6032 - accuracy: 0.0238
Epoch 17/400
230/230 - 3s - loss: 5.5129 - accura

KeyboardInterrupt: 

In [ ]:
# visual
fig, axes = plt.subplots(10,8, figsize=(15,15))
ax = plt.gca()
ax.axes.xaxis.set_visible(False)
ax.axes.yaxis.set_visible(False)

test_real = list()
test_predict = list()

power_info = 1

for i in range(0, round(len(test_X) / 24)):
    start_idx = 24 * i
    end_idx = (24 * (i + 1))
    
    real_pattern = test_X[end_idx-1][-23:]
    real_pattern = np.append(real_pattern, [test_y[end_idx-1]])
    
    test_real.append(real_pattern)
#     print("real_pattern:",real_pattern)
    
    predict_pattern = test_X[start_idx+power_info][-power_info:].tolist()

    for p in range(start_idx + power_info, end_idx):
        result = model_2.predict_classes([test_X[p].tolist()])
        predict_pattern.append(y[result[0]])
    test_predict.append(predict_pattern)
    
#     print("predict_pattern:", predict_pattern)

for pi in range(0, len(test_real)):
    sns.lineplot(data=test_real[pi], label="real", lw=2, color="blue", ax=axes[int(pi / 8)][pi % 8], legend=False)
    sns.lineplot(data=test_predict[pi], label="predict", lw=2, color="red", ax=axes[int(pi / 8)][pi % 8], legend=False)

In [ ]:
# visual
fig, axes = plt.subplots(10,8, figsize=(15,15))
ax = plt.gca()
ax.axes.xaxis.set_visible(False)
ax.axes.yaxis.set_visible(False)

test_real = list()
test_predict = list()

power_info = 5

for i in range(0, round(len(test_X) / 24)):
    start_idx = 24 * i
    end_idx = (24 * (i + 1))
    
    real_pattern = test_X[end_idx-1][-23:]
    real_pattern = np.append(real_pattern, [test_y[end_idx-1]])
    
    test_real.append(real_pattern)
#     print("real_pattern:",real_pattern)
    
    predict_pattern = test_X[start_idx+power_info][-power_info:].tolist()

    for p in range(start_idx + power_info, end_idx):
        result = model_2.predict_classes([test_X[p].tolist()])
        predict_pattern.append(y[result[0]])
    test_predict.append(predict_pattern)
    
#     print("predict_pattern:", predict_pattern)

for pi in range(0, len(test_real)):
    sns.lineplot(data=test_real[pi], label="real", lw=2, color="blue", ax=axes[int(pi / 8)][pi % 8], legend=False)
    sns.lineplot(data=test_predict[pi], label="predict", lw=2, color="red", ax=axes[int(pi / 8)][pi % 8], legend=False)

In [ ]:
# visual
fig, axes = plt.subplots(10,8, figsize=(15,15))
ax = plt.gca()
ax.axes.xaxis.set_visible(False)
ax.axes.yaxis.set_visible(False)

test_real = list()
test_predict = list()

power_info = 10

for i in range(0, round(len(test_X) / 24)):
    start_idx = 24 * i
    end_idx = (24 * (i + 1))
    
    real_pattern = test_X[end_idx-1][-23:]
    real_pattern = np.append(real_pattern, [test_y[end_idx-1]])
    
    test_real.append(real_pattern)
#     print("real_pattern:",real_pattern)
    
    predict_pattern = test_X[start_idx+power_info][-power_info:].tolist()

    for p in range(start_idx + power_info, end_idx):
        result = model_2.predict_classes([test_X[p].tolist()])
        predict_pattern.append(y[result[0]])
    test_predict.append(predict_pattern)
    
#     print("predict_pattern:", predict_pattern)

for pi in range(0, len(test_real)):
    sns.lineplot(data=test_real[pi], label="real", lw=2, color="blue", ax=axes[int(pi / 8)][pi % 8], legend=False)
    sns.lineplot(data=test_predict[pi], label="predict", lw=2, color="red", ax=axes[int(pi / 8)][pi % 8], legend=False)

In [ ]:
# visual
fig, axes = plt.subplots(10,8, figsize=(15,15))
ax = plt.gca()
ax.axes.xaxis.set_visible(False)
ax.axes.yaxis.set_visible(False)

test_real = list()
test_predict = list()

power_info = 15

for i in range(0, round(len(test_X) / 24)):
    start_idx = 24 * i
    end_idx = (24 * (i + 1))
    
    real_pattern = test_X[end_idx-1][-23:]
    real_pattern = np.append(real_pattern, [test_y[end_idx-1]])
    
    test_real.append(real_pattern)
#     print("real_pattern:",real_pattern)
    
    predict_pattern = test_X[start_idx+power_info][-power_info:].tolist()

    for p in range(start_idx + power_info, end_idx):
        result = model_2.predict_classes([test_X[p].tolist()])
        predict_pattern.append(y[result[0]])
    test_predict.append(predict_pattern)
    
#     print("predict_pattern:", predict_pattern)

for pi in range(0, len(test_real)):
    sns.lineplot(data=test_real[pi], label="real", lw=2, color="blue", ax=axes[int(pi / 8)][pi % 8], legend=False)
    sns.lineplot(data=test_predict[pi], label="predict", lw=2, color="red", ax=axes[int(pi / 8)][pi % 8], legend=False)

In [ ]:
model_2.save("model/아파트1-101-1602")

In [282]:
# from tensorflow.keras.models import load_model
# test_save_model = load_model("model/아파트1-104-1206")
# test_save_model.summary()

Model: "sequential_22"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_21 (Embedding)     (None, 28, 10)            69360     
_________________________________________________________________
lstm_22 (LSTM)               (None, 128)               71168     
_________________________________________________________________
dense_22 (Dense)             (None, 6936)              894744    
Total params: 1,035,272
Trainable params: 1,035,272
Non-trainable params: 0
_________________________________________________________________


In [284]:
client.close()